###################
# UseOpenCV.cmake #
###################

OPTION(WITH_OPENCV "Build with OpenCV support?" ON)

IF(WITH_OPENCV)
  FIND_PACKAGE(OpenCV 3.4.0 REQUIRED )
  INCLUDE_DIRECTORIES(BEFORE SYSTEM ${OpenCV_INCLUDE_DIRS})
  ADD_DEFINITIONS(-DWITH_OPENCV)
ENDIF()
